config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sessions, only: %i[new create destroy]
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :attendances
  resources :users, only: %i[new create show]
  resources :events, except: %i[update edit]
  root to: 'events#index'
end

app/models/application_record.rb
# rubocop:disabled Style/Documentation
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
# rubocop:enabled Style/Documentation

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :event, class_name: 'Event'

  validates_uniqueness_of :user, scope: :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :user, dependent: :destroy
  validates :name, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :description, presence: true
  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past, -> { where('date < ? ', DateTime.now) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances
  has_many :events, dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event, dependent: :destroy
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# rubocop:disable Style/GuardClause
class ApplicationController < ActionController::Base
  helper_method :current_user, :log_in
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id:
      session[:user_id])
    end
  end
end
# rubocop:enable Style/GuardClause

app/controllers/attendances_controller.rb
# rubocop:disabled Style/Documentation
class AttendancesController < ApplicationController
  def create
    @attendance = Attendance.new(attendances_params)
    if @attendance.save
      flash[:success] = 'you are now attending this event'
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = 'already attending'
    end
  end

  def destroy
    @attendance = Attendance.find_by(user_id: attendances_params[:user_id])
    redirect_to event_path(attendances_params[:event_id]) if @attendance.destroy
  end

  private

  def attendances_params
    params.require(:attendance).permit(:user_id, :event_id)
  end
end
# rubocop:enabled Style/Documentation

app/controllers/events_controller.rb
# rubocop:disabled Style/Documentation
class EventsController < ApplicationController
  before_action :set_event, only: %i[show destroy]
  def index
    @events = Event.all
    @upcoming = Event.upcoming.sort { |a, b| b.date <=> a.date }
    @past = Event.past.sort { |a, b| b.date <=> a.date }
  end

  def new
    if current_user
      @event = Event.new
    else
      redirect_to signup_path
    end
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = 'event successfully created '
      redirect_to events_path
    else
      flash.now[:danger] = 'error with some fields'
      render 'new'
    end
  end

  def show
    @attendance = Attendance.new
    @event = Event.find(params[:id])
    @users_not_in = User.all.where.not(id: @event.attendees).where.not(id: current_user)
  end

  def destroy
    @event.destroy
    flash[:succes] = 'event destroyed successfuly'
    redirect_to root_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :location, :date, :description)
  end
end
# rubocop:enabled Style/Documentation

app/controllers/sessions_controller.rb
# rubocop:disabled Style/Documentation
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user
      log_in user
      flash[:success] = 'logged in with success'
      redirect_to events_path
    else
      flash.now[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to login_path
  end
end
# rubocop:enabled Style/Documentation

app/controllers/users_controller.rb
# rubocop:disabled Style/Documentation
class UsersController < ApplicationController
  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'user successfully created'
      redirect_to @user
    else
      flash.now[:error] = "Error: #{@user.errors.full_messages.join(', ')}"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = Event.past.order(date: :ASC)
    @past_events = Event.upcoming.order(date: :DESC)
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end
# rubocop:enabled Style/Documentation

app/helpers/application_helper.rb
# rubocop:disabled Style/Documentation
module ApplicationHelper
end
# rubocop:enabled Style/Documentation

app/helpers/attendances_helper.rb
# rubocop:disabled Style/Documentation
module AttendancesHelper
  def attendance_exist?(event_id, user_id)
    'd-none' if Attendance.find_by(event_id: event_id, user_id: user_id)
  end

  def attendance_not_exist?(event_id, user_id)
    'd-none' if Attendance.find_by(event_id: event_id, user_id: user_id).blank?
  end

  def attendance
    attendance.all
  end
end
# rubocop:enabled Style/Documentation

app/helpers/events_helper.rb
# rubocop:disabled Style/Documentation
module EventsHelper
end
# rubocop:enabled Style/Documentation

app/helpers/sessions_helper.rb
# rubocop:disabled Style/Documentation
module SessionsHelper
end
# rubocop:enabled Style/Documentation

app/helpers/users_helper.rb
# rubocop:disabled Style/Documentation
module UsersHelper
  def current_user_upcoming_event
    current_user.attended_events.where('date >= ?', DateTime.now)
  end

  def current_user_past_event
    current_user.attended_events.where('date < ? ', DateTime.now)
  end
end
# rubocop:enabled Style/Documentation

app/views/events/index.html.erb
<h3 class="text-center">page for all events</h3>

<% if current_user %>
  <div class="container">
    <div class="row">
      <div class="col-6">

        <div class="text-center">
          event name
        </div>
      </div>
      <div class="col-6">
        <div class="text-center">
          event creator
        </div>
      </div>
    </div>
    <div class="row border">
      <% @events.each do |event| %>
        <div class="col-6">
          <div>
            <%= link_to event.name,event_path(event.id) %>
          </div>
        </div>
        <div class="col-6">
          <div>
            <%= event.user.username %>
          </div>
        </div>
        <%end%>
    </div>
  </div>
  </div>

  <%else%>
    <% @events.each do |event| %>
      <ul class="list-unstyled">
        <li>
          <%= event.name%>
        </li>
      </ul>
      <% end %>
        <% end %>
       <div class="upcoming-cont">
    <% if @upcoming.any? %>
      <h2>Upcoming Events</h2>
      <ul class = "upcoming">
        <% @upcoming.each do |e| %>
            <li>
              <% if current_user %>
                <%= link_to  e.name, event_path(e.id) %>
              <% else %>
                <%= link_to  e.name, signup_path %>
              <% end %>
              <div>
               
              </div>
            </li>
        <%end%>
      </ul>
    <% end %>
  </div>
     <div class="past-cont">
    <% if @past.any? %>
      <h2>past Events</h2>
      <ul class = "past">
        <% @past.each do |e| %>
            <li>
              <% if current_user %>
                <%= link_to  e.name, event_path(e.id) %>
              <% else %>
                <%= link_to  e.name, signup_path %>
              <% end %>
              <div>
               
              </div>
            </li>
        <%end%>
      </ul>
    <% end %>
  </div>

app/views/events/new.html.erb
<div class="row">
<div class="col-lg-12 col-md-6 col-6 d-flex flex-column  align-items-center justify-content-center">
<h3 class="text-center">form for events</h3>
<%=form_with model: @event do |f|%>
<div>
<%= f.label :name %>
<%= f.text_field :name%>
</div>
<div>
<%= f.label :location %>
<%= f.text_field :location%>
</div>
<div>
<%= f.label :date %>
<%= f.datetime_field :date%>
</div>
<div>
<%= f.label :description %>
<%= f.text_area :description %>
</div>
<div>
<%= f.submit%></div>
<%end%>
</div>
</div>

app/views/events/show.html.erb
<h3 class="text-center">event created</h3>
<div class="container">
  <div class="row">
    <div class="col-3">
      <div>event name</div>
    </div>
     <div class="col-3">
      <div>event location</div>
    </div>
    <div class="col-3">
      <div>event description</div>
    </div>
    <div class="col-3">
      <div>event date</div>
    </div>
  </div>
  <div class="row">
    <% if current_user%>
    <div class="col-2">
      <div> <%= @event.name%> </div>
    </div>
    <div class="col-3">
      <div> <%= @event.location%></div>
    </div>
    <div class="col-3">
      <div> <%= @event.description%></div>
    </div>
    <div class="col-2">
      <div>  <%= @event.date%> </div>
    </div>
    <div class="col-2">
          <div>
            <%= link_to 'delete', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
    </div>
    <% end %>
  </div>
 </div>

<%= form_for  @attendance  do |f| %>

<%= f.hidden_field :event_id, :value => params[:id] %>
<%= f.hidden_field :user_id, :value => current_user.id%>
<%= f.submit "Attend", class: "#{attendance_exist?(params[:id],current_user.id)} "%>
<% end %>

<%= form_for  @attendance,method: :delete, url: attendance_path  do |f| %>
    <%= f.hidden_field :event_id, :value => params[:id] %>
    <%= f.hidden_field :user_id, :value => current_user[:id] %>
    <%= f.submit "unattend", class: "#{attendance_not_exist?(params[:id],current_user.id)} px-2 inline-flex "%>
<% end %>
<% if @users_not_in.any? %>
    <h3>Invite user</h3>
    <%= form_for @attendance do |f| %>
      <%= f.hidden_field  :event_id, :value => params[:id] %>
      <%= select("user", "user_id", @users_not_in.collect {|p| [ p.username, p.id ] }, class: 'invitee') %>
      <%= f.submit 'Invite', class: 'invite-btn' %>
    <% end %>
  <% end %>

<% if @event.attendees.any? %>
<h3 class="text-center mt-2">Attendees</h3>
<ul class="list-unstyled">
  <% @event.attendees.each do |a| %>
    <li>
      <%= a.username %>
    </li>
  <% end %>
</ul>
<% else %>
<p>no event attendance yet</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PrivateEvent</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
      <nav class="navbar-expand-lg bg-dark d-flex justify-content-between mt-3">
        <div class="form-title text-white w-25">
          <span>private events</span>
        </div>
        <ul class="d-flex justify-content-between text-white w-50 list-unstyled">
          <% if current_user%>
            <li class="w-25">
              <%= link_to 'logout' , logout_path, method: :delete %>
            </li>
            <li class="w-25">
              <%= link_to 'create event' , new_event_path %>
            </li>
            <li class="w-25">
              <%= link_to 'events' , events_path %>
            </li>
            <li><%= link_to current_user.username, user_path(current_user) %></li>
            <%else%>
              <li class="w-25">
                <%= link_to 'login' , login_path %>
              </li>
              <li><%= link_to "Signup now!" , signup_path %>
              <li><%= link_to 'events', events_path %></li>
              <li><%= link_to 'create event', new_event_path %></li>
              </li>
              <%end%>

        </ul>
      </nav>
       <% flash.each do |name, message| %>
    <div class="<%= name %> text-center alert alert-info ">
      <%= message %>
    </div>
    <% end %>
      <%= yield %>
</body>

</html>

app/views/users/new.html.erb
<p class="text-center">New User form</p>
<div class="row">
<div class="col-12 col-md-10 col-lg-12 d-flex flex-column align-items-center">
  <%= form_with model: @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.submit %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<h4>list of all your events</h4>
<% current_user.events.each do |event| %>
<p><%= link_to event.name, event_path(event.id) %></p>
<%end%>
</div>
<h3>events you are attending</h3>
<% if current_user.attended_events.any? %>
<% current_user.attended_events.each do |event| %>
<ul class="list-unstyled">
<li><%= event.name%></li>
</ul>

  <%end%>
<% end %>
<div>
    <p class="text-center">upcoming events you are attending</p>
      <% if  current_user_upcoming_event.any? %>
        <%  current_user_upcoming_event.each  do |e|  %>
       <p> <%=e.name%></p>
        <% end %>
        
      <% end %>  
    <p class="text-center">past events you attended</p>
     
        <% if  current_user_past_event.any? %>
        <%  current_user_past_event.each  do |e|  %>
        <p> <%=e.name%></p>
        <% end %>
       <% else %>
       <p>no past events yet</p>
       
       
       <% end %>
       
    
</div>